name: CI/CD Pipeline

on:
  push
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.1'
        cache: 'npm'
       
    - run: npm ci
    - run: npm test

      

      #this commit is test. I am now updating this. generating an error..





